name: furever_home
description: "MAP Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  http: ^1.2.2
  image_picker: ^1.2.0
  google_sign_in: ^7.2.0
  firebase_app_check: ^0.4.1
  firebase_storage: ^13.0.2
  audioplayers: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
  fonts:
    - family: Boyers
      fonts:
        - asset: assets/fonts/Boyers-Regular-BF656d77750b513.otf
